name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python with caching
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: >
          pyinstaller --noconfirm --clean --onefile 
          --add-binary="7z\7z.exe:7z" 
          --add-data="icons\favicon.ico:icons" 
          --icon="icons\details_icon.png" 
          --name DazContentInstaller 
          main.pyw

      - name: Prepare distribution package
        shell: pwsh
        run: |
          $targetDir = "dist/DazContentInstaller"
          New-Item -Path $targetDir -ItemType Directory -Force  
          Copy-Item config.ini -Destination $targetDir/
          Move-Item dist/DazContentInstaller.exe -Destination $targetDir/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: DazContentInstaller
          path: dist
