name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '>=3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --add-binary "7z/7z.exe;7z" --onefile main.pyw --name DazContentInstaller

      - name: Create package directory
        run: mkdir -p dist/DazContentInstaller
        
      - name: Create logger directory
        run: mkdir -p dist/DazContentInstaller/logs
        
      - name: Copy config.ini file
        run: cp config.ini dist/DazContentInstaller/

      - name: Move the built binary
        run: mv dist/DazContentInstaller.exe dist/DazContentInstaller/


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: DazContentInstaller
          path: dist/
